[package]
name = "ib_rtt_tester"
version = "0.1.0"
authors = ["ipshiv <ipshiv@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
probe-rs-rtt = "0.12.0"
clap = "2.34.0"
chrono = "0.4.19"
